// <auto-generated />
using System;
using BTCPayServer.Plugins.Payjoin;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.Plugins.Payjoin.Migrations
{
    [DbContext(typeof(PayjoinPluginDbContext))]
    partial class PayjoinPluginDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.Plugins.Payjoin")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTCPayServer.Plugins.Payjoin.Data.PayjoinReceiverSessionData", b =>
                {
                    b.Property<string>("InvoiceId")
                        .HasColumnType("text");

                    b.Property<int?>("CloseInvoiceStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CloseRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ContributedInputOutputIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ContributedInputTransactionId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCloseRequested")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("MonitoringExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OhttpRelayUrl")
                        .HasColumnType("text");

                    b.Property<string>("ReceiverAddress")
                        .HasColumnType("text");

                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("InvoiceId");

                    b.ToTable("ReceiverSessions", "BTCPayServer.Plugins.Payjoin");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Payjoin.Data.PayjoinReceiverSessionEventData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Event")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId", "Sequence")
                        .IsUnique();

                    b.ToTable("ReceiverSessionEvents", "BTCPayServer.Plugins.Payjoin");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Payjoin.Data.PluginData", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PluginRecords", "BTCPayServer.Plugins.Payjoin");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Payjoin.Data.PayjoinReceiverSessionEventData", b =>
                {
                    b.HasOne("BTCPayServer.Plugins.Payjoin.Data.PayjoinReceiverSessionData", "Session")
                        .WithMany("Events")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Payjoin.Data.PayjoinReceiverSessionData", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
