// <auto-generated />
using System;
using BTCPayServer.Plugins.Payjoin;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.Plugins.Payjoin.Migrations
{
    [DbContext(typeof(PayjoinPluginDbContext))]
    partial class PayjoinPluginDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.Plugins.Payjoin")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTCPayServer.Plugins.Payjoin.Data.PayjoinReceiverInputReservationData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OutputIndex")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ReservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id")
                        .HasName("PK_ReceiverInputReservations");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_ReceiverInputReservations_ExpiresAt");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("IX_ReceiverInputReservations_InvoiceId");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("IX_ReceiverInputReservations_StoreId");

                    b.HasIndex("TransactionId", "OutputIndex")
                        .IsUnique()
                        .HasDatabaseName("IX_ReceiverInputReservations_TransactionId_OutputIndex");

                    b.ToTable("ReceiverInputReservations", "BTCPayServer.Plugins.Payjoin");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Payjoin.Data.PayjoinReceiverSessionData", b =>
                {
                    b.Property<string>("InvoiceId")
                        .HasColumnType("text");

                    b.Property<int?>("CloseInvoiceStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CloseRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ContributedInputOutputIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("ContributedInputTransactionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("InitializedPollAfterCloseRequestConsumed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCloseRequested")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("MonitoringExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OhttpRelayUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ReceiverAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("InvoiceId")
                        .HasName("PK_ReceiverSessions");

                    b.ToTable("ReceiverSessions", "BTCPayServer.Plugins.Payjoin");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Payjoin.Data.PayjoinReceiverSessionEventData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_ReceiverSessionEvents");

                    b.HasIndex("InvoiceId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("IX_ReceiverSessionEvents_InvoiceId_Sequence");

                    b.ToTable("ReceiverSessionEvents", "BTCPayServer.Plugins.Payjoin");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Payjoin.Data.PayjoinReceiverInputReservationData", b =>
                {
                    b.HasOne("BTCPayServer.Plugins.Payjoin.Data.PayjoinReceiverSessionData", "Session")
                        .WithMany("InputReservations")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ReceiverInputReservations_ReceiverSessions_InvoiceId");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Payjoin.Data.PayjoinReceiverSessionEventData", b =>
                {
                    b.HasOne("BTCPayServer.Plugins.Payjoin.Data.PayjoinReceiverSessionData", "Session")
                        .WithMany("Events")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ReceiverSessionEvents_ReceiverSessions_InvoiceId");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.Payjoin.Data.PayjoinReceiverSessionData", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("InputReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
