name: build

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

env:
  RUSTUP_TOOLCHAIN: 1.85.0
  TESTS_BTCRPCCONNECTION: "server=http://127.0.0.1:43782;ceiwHEbqWI83:DwubwWsoo3"
  TESTS_BTCNBXPLORERURL: "http://127.0.0.1:32838/"
  TESTS_POSTGRES: "User ID=postgres;Include Error Detail=true;Host=127.0.0.1;Port=39372;Database=btcpayserver"
  TESTS_EXPLORER_POSTGRES: "User ID=postgres;Include Error Detail=true;Host=127.0.0.1;Port=39372;Database=nbxplorer"
  TESTS_MAILPIT_HOST: "127.0.0.1"
  TESTS_MAILPIT_SMTP: "34219"
  TESTS_MAILPIT_HTTP: "34218"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Payjoin CI
        uses: ./.github/actions/prepare-ci-build
        with:
          rust-toolchain: ${{ env.RUSTUP_TOOLCHAIN }}

      - name: Run unit tests
        run: dotnet test "BTCPayServer.Plugins.Payjoin.Tests/BTCPayServer.Plugins.Payjoin.Tests.csproj" -c Release --no-build --no-restore

      - name: Set up BTCPay integration test environment
        uses: ./.github/actions/prepare-integration-test-env

      - name: Run integration tests
        run: dotnet test "BTCPayServer.Plugins.Payjoin.IntegrationTests/BTCPayServer.Plugins.Payjoin.IntegrationTests.csproj" -c Release --no-build --no-restore

      - name: Stop BTCPay integration test infrastructure
        if: always()
        run: docker compose -f btcpayserver/BTCPayServer.Tests/docker-compose.yml down -v >/dev/null 2>&1
